name: CI
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  merge_group: # GitHub Merge Queue
jobs:
  finalize:
    timeout-minutes: 10
    needs: [test]
    if: always() # Important: Make sure that this job runs even if the tests fail.
    runs-on: ubuntu-latest # GitHub-hosted runners
    steps:
      - run: |
          echo test: ${{ needs.test.result }}
      - run: exit 1
        # Every line except the last line must end with `||`.
        # The last line must NOT end with `||`.
        if: (needs.test.result != 'success')

  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.6'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          # This is a public repo.
          # We are using v4 of the codecov-action.
          # If the PR is from a fork, then Codecov allows us to use
          # tokenless Codecov uploads.
          # If the PR is not from a fork, then Codecov does not allow
          # us to use tokenless Codecov uploads, and thus we must use
          # the token.
          # Tokenless Codcov uploads are prone to random failures,
          # due to Codecov's servers hitting GitHub rate limits.
          # Therefore:
          # 1. If this CI run is not a PR run, we set `fail_ci_if_error` to `true`.
          # 2. If this CI run is a PR run and the PR is not from a fork, we set `fail_ci_if_error` to `true`.
          # 3. If this CI run is a PR run and the PR is from a fork, we set `fail_ci_if_error` to `false`.
          fail_ci_if_error: ${{ (github.event_name != 'pull_request') || (github.repository == github.event.pull_request.head.repo.full_name) }}
          token: ${{ secrets.CODECOV_TOKEN }}